@api = http://localhost:4000/bitacora

GET {{api}}

###

GET {{api}}/1

###

POST {{api}}
Content-Type: application/json

{
    "titulo": "pruebaapi",
    "contenido": "pruebaapi",
    "practica": 1,
    "posttime": "2023-01-01T00:00:00.000Z",
    "calificacionProfesor": null
}

###

DELETE {{api}}/12

###

PUT {{api}}/12
Content-Type: application/json

{
    "titulo": "PRUEBA",
    "contenido": "PRUEBA",
    "practica": 1,
    "posttime": "2023-01-01T00:00:00.000Z",
    "calificacionProfesor": 100
}