USE [master]
GO
/****** Object:  Database [ACS]    Script Date: 11/17/2023 7:19:13 AM ******/
CREATE DATABASE [ACS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ACS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ACS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ACS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ACS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ACS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ACS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ACS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ACS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ACS] SET ARITHABORT OFF 
GO
ALTER DATABASE [ACS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ACS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ACS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ACS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ACS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ACS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ACS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ACS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ACS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ACS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ACS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ACS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ACS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ACS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ACS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ACS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ACS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ACS] SET RECOVERY FULL 
GO
ALTER DATABASE [ACS] SET  MULTI_USER 
GO
ALTER DATABASE [ACS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ACS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ACS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ACS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ACS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ACS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ACS', N'ON'
GO
ALTER DATABASE [ACS] SET QUERY_STORE = ON
GO
ALTER DATABASE [ACS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ACS]
GO
/****** Object:  Table [dbo].[Bitacora]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bitacora](
	[id] [tinyint] IDENTITY(1,1) NOT NULL,
	[titulo] [nvarchar](100) NOT NULL,
	[contenido] [nvarchar](max) NOT NULL,
	[practica] [smallint] NOT NULL,
	[posttime] [datetime] NOT NULL,
	[calificacionProfesor] [tinyint] NULL,
 CONSTRAINT [PK_Bitacora] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ComentarioBitacora]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ComentarioBitacora](
	[id] [smallint] IDENTITY(1,1) NOT NULL,
	[bitacora] [tinyint] NOT NULL,
	[autor] [int] NOT NULL,
	[contenido] [nvarchar](max) NOT NULL,
	[posttime] [datetime] NOT NULL,
 CONSTRAINT [PK_ComentarioBitacora] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ComentarioInforme]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ComentarioInforme](
	[id] [smallint] IDENTITY(1,1) NOT NULL,
	[informe] [tinyint] NOT NULL,
	[autor] [int] NOT NULL,
	[contenido] [nvarchar](max) NOT NULL,
	[posttime] [datetime] NOT NULL,
 CONSTRAINT [PK_ComentarioInforme] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empresa]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empresa](
	[id] [int] NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[telefono] [nchar](20) NOT NULL,
 CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[id] [int] NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[apellido] [nvarchar](100) NOT NULL,
	[carnet] [nchar](10) NOT NULL,
	[carrera] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_Estudiante] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Informe]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Informe](
	[id] [tinyint] IDENTITY(1,1) NOT NULL,
	[titulo] [nvarchar](100) NOT NULL,
	[contenido] [nvarchar](max) NOT NULL,
	[practica] [smallint] NOT NULL,
	[posttime] [datetime] NOT NULL,
	[calificacionProfesor] [tinyint] NULL,
	[calificacionEmpresa] [tinyint] NULL,
	[calificacionTotal] [tinyint] NULL,
 CONSTRAINT [PK_Informe] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PracticaProfesional]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PracticaProfesional](
	[id] [smallint] IDENTITY(1,1) NOT NULL,
	[estudiante] [int] NOT NULL,
	[profesor] [int] NOT NULL,
	[empresa] [int] NOT NULL,
	[calificacionFinal] [tinyint] NULL,
	[fechaInicio] [datetime] NOT NULL,
	[fechaFinal] [datetime] NOT NULL,
	[estado] [nvarchar](50) NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_PracticaProfesional] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesor]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor](
	[id] [int] NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[apellido] [nvarchar](100) NOT NULL,
	[escuela] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_Profesor] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoUsuario]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoUsuario](
	[id] [tinyint] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TipoUsuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 11/17/2023 7:19:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[correo] [nvarchar](300) NOT NULL,
	contrasena [nvarchar](100) NOT NULL,
	[tipo] [tinyint] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bitacora]  WITH CHECK ADD  CONSTRAINT [FK_Bitacora_PracticaProfesional] FOREIGN KEY([practica])
REFERENCES [dbo].[PracticaProfesional] ([id])
GO
ALTER TABLE [dbo].[Bitacora] CHECK CONSTRAINT [FK_Bitacora_PracticaProfesional]
GO
ALTER TABLE [dbo].[ComentarioBitacora]  WITH CHECK ADD  CONSTRAINT [FK_ComentarioBitacora_Bitacora] FOREIGN KEY([bitacora])
REFERENCES [dbo].[Bitacora] ([id])
GO
ALTER TABLE [dbo].[ComentarioBitacora] CHECK CONSTRAINT [FK_ComentarioBitacora_Bitacora]
GO
ALTER TABLE [dbo].[ComentarioBitacora]  WITH CHECK ADD  CONSTRAINT [FK_ComentarioBitacora_Usuario] FOREIGN KEY([autor])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[ComentarioBitacora] CHECK CONSTRAINT [FK_ComentarioBitacora_Usuario]
GO
ALTER TABLE [dbo].[ComentarioInforme]  WITH CHECK ADD  CONSTRAINT [FK_ComentarioInforme_Informe] FOREIGN KEY([informe])
REFERENCES [dbo].[Informe] ([id])
GO
ALTER TABLE [dbo].[ComentarioInforme] CHECK CONSTRAINT [FK_ComentarioInforme_Informe]
GO
ALTER TABLE [dbo].[ComentarioInforme]  WITH CHECK ADD  CONSTRAINT [FK_ComentarioInforme_Usuario] FOREIGN KEY([autor])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[ComentarioInforme] CHECK CONSTRAINT [FK_ComentarioInforme_Usuario]
GO
ALTER TABLE [dbo].[Empresa]  WITH CHECK ADD  CONSTRAINT [FK_Empresa_Usuario] FOREIGN KEY([id])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[Empresa] CHECK CONSTRAINT [FK_Empresa_Usuario]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_Estudiante_Usuario] FOREIGN KEY([id])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_Estudiante_Usuario]
GO
ALTER TABLE [dbo].[Informe]  WITH CHECK ADD  CONSTRAINT [FK_Informe_PracticaProfesional] FOREIGN KEY([practica])
REFERENCES [dbo].[PracticaProfesional] ([id])
GO
ALTER TABLE [dbo].[Informe] CHECK CONSTRAINT [FK_Informe_PracticaProfesional]
GO
ALTER TABLE [dbo].[PracticaProfesional]  WITH CHECK ADD  CONSTRAINT [FK_PracticaProfesional_Usuario] FOREIGN KEY([estudiante])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[PracticaProfesional] CHECK CONSTRAINT [FK_PracticaProfesional_Usuario]
GO
ALTER TABLE [dbo].[PracticaProfesional]  WITH CHECK ADD  CONSTRAINT [FK_PracticaProfesional_Usuario1] FOREIGN KEY([profesor])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[PracticaProfesional] CHECK CONSTRAINT [FK_PracticaProfesional_Usuario1]
GO
ALTER TABLE [dbo].[PracticaProfesional]  WITH CHECK ADD  CONSTRAINT [FK_PracticaProfesional_Usuario2] FOREIGN KEY([empresa])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[PracticaProfesional] CHECK CONSTRAINT [FK_PracticaProfesional_Usuario2]
GO
ALTER TABLE [dbo].[Profesor]  WITH CHECK ADD  CONSTRAINT [FK_Profesor_Usuario] FOREIGN KEY([id])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[Profesor] CHECK CONSTRAINT [FK_Profesor_Usuario]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_TipoUsuario] FOREIGN KEY([tipo])
REFERENCES [dbo].[TipoUsuario] ([id])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_TipoUsuario]
GO
USE [master]
GO
ALTER DATABASE [ACS] SET  READ_WRITE 
GO
